import { Send, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { useClientContext } from "@/hooks/useClientContext";
import { useClientDeliverables } from "@/hooks/useDeliverables";
import { deliverableStatusLabel } from "@/lib/copilotStyles";
import { useCopilotContext } from "@/components/copilot/CopilotProvider";

const DeliverablesTab = () => {
  const { selectedClientId, selectedClient } = useClientContext();
  const { data: rawDeliverables = [] } = useClientDeliverables(selectedClientId);
  const { togglePanel } = useCopilotContext();

  interface DbDeliverable {
    id: string;
    title: string;
    status: string;
    engine?: string | null;
  }

  const deliverables = (rawDeliverables as DbDeliverable[]).map((d) => ({
    id: d.id,
    title: d.title,
    client: selectedClient.name,
    status: d.status ?? "needs_data",
    engine: d.engine ?? "",
  }));

  if (deliverables.length === 0) {
    return (
      <div className="text-center py-6 space-y-3">
        <FileText className="w-8 h-8 text-muted-foreground mx-auto" />
        <div className="space-y-1">
          <p className="text-sm font-medium text-foreground">No deliverables yet</p>
          <p className="text-xs text-muted-foreground max-w-xs mx-auto">
            Deliverables are client-ready outputs generated by Quarterback AI — quarterly reviews, status updates, meeting recaps, and strategic memos.
          </p>
        </div>
        <button
          onClick={togglePanel}
          className="inline-flex items-center gap-1.5 text-xs font-medium text-primary hover:underline"
        >
          Open Quarterback to generate one
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-2">
      <p className="text-xs text-muted-foreground pb-1">
        AI-generated documents ready to review, approve, or send to your client.
      </p>
      {deliverables.map((del) => {
        const st = (deliverableStatusLabel as Record<string, { label: string; style: string }>)[del.status]
          ?? { label: del.status, style: "bg-muted text-muted-foreground" };
        return (
          <div
            key={del.id}
            className="flex items-center justify-between p-3 rounded-md border border-border hover:bg-muted/30 transition-colors"
          >
            <div>
              <p className="text-sm font-medium text-foreground">{del.title}</p>
              <p className="text-[10px] text-muted-foreground">{del.client}</p>
            </div>
            <div className="flex items-center gap-2">
              <span className={cn("text-[10px] font-medium px-2 py-0.5 rounded-full", st.style)}>
                {st.label}
              </span>
              {del.status === "ready" && (
                <Button variant="ghost" size="sm" className="text-xs h-7">
                  <Send className="w-3 h-3" />
                </Button>
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
};

export default DeliverablesTab;
