import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
  AlignmentType,
} from "docx";

export interface DeliverableDocxInput {
  title: string;
  clientName: string;
  generatedAt: string;
  markdownContent: string;
}

/**
 * Parse inline markdown spans within a single line of text.
 * Supports **bold**, *italic*, and plain text.
 * Returns an array of TextRun objects.
 */
function parseInlineSpans(text: string): TextRun[] {
  const runs: TextRun[] = [];
  // Match **bold**, *italic*, or plain text chunks
  const regex = /\*\*(.+?)\*\*|\*(.+?)\*|([^*]+)/g;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(text)) !== null) {
    if (match[1] !== undefined) {
      runs.push(new TextRun({ text: match[1], bold: true }));
    } else if (match[2] !== undefined) {
      runs.push(new TextRun({ text: match[2], italics: true }));
    } else if (match[3] !== undefined) {
      runs.push(new TextRun({ text: match[3] }));
    }
  }
  return runs.length > 0 ? runs : [new TextRun({ text })];
}

/**
 * Parse a markdown string into docx Paragraph nodes.
 * Supported syntax:
 *   # H1  |  ## H2  |  ### H3
 *   - bullet items (leading `- ` or `* `)
 *   blank lines → spacing only
 *   **bold** and *italic* inline spans
 *   any other line → normal paragraph
 */
function parseMarkdownToParagraphs(markdown: string): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  const lines = markdown.split("\n");

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();

    // Blank line — add a small spacer
    if (line.trim() === "") {
      paragraphs.push(new Paragraph({ children: [new TextRun({ text: "" })] }));
      continue;
    }

    // H1
    if (line.startsWith("# ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 240, after: 120 },
          children: [new TextRun({ text: line.slice(2).trim(), bold: true })],
        })
      );
      continue;
    }

    // H2
    if (line.startsWith("## ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 200, after: 80 },
          children: [new TextRun({ text: line.slice(3).trim(), bold: true })],
        })
      );
      continue;
    }

    // H3
    if (line.startsWith("### ")) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 160, after: 60 },
          children: [new TextRun({ text: line.slice(4).trim(), bold: true })],
        })
      );
      continue;
    }

    // Bullet (- or *)
    if (/^[-*] /.test(line)) {
      const bulletText = line.slice(2).trim();
      paragraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          children: parseInlineSpans(bulletText),
        })
      );
      continue;
    }

    // Italics-only line (e.g. *Prepared …*)
    if (line.startsWith("*") && line.endsWith("*") && !line.startsWith("**")) {
      paragraphs.push(
        new Paragraph({
          spacing: { after: 80 },
          children: [new TextRun({ text: line.slice(1, -1), italics: true, color: "555555" })],
        })
      );
      continue;
    }

    // Normal paragraph — parse inline spans
    paragraphs.push(
      new Paragraph({
        spacing: { after: 100 },
        children: parseInlineSpans(line),
      })
    );
  }

  return paragraphs;
}

/**
 * Build a .docx Buffer for a deliverable document.
 * Parses markdown (h1/h2/h3, paragraphs, bullets, **bold**, *italic*)
 * and emits Word-compatible output that opens cleanly in Google Docs and Word.
 */
export async function buildDeliverableDocx(input: DeliverableDocxInput): Promise<Buffer> {
  const children: Paragraph[] = [];

  // Document header: client name + generated date
  children.push(
    new Paragraph({
      spacing: { after: 80 },
      children: [
        new TextRun({ text: input.clientName, bold: true }),
        new TextRun({ text: `  ·  Generated ${input.generatedAt}` }),
      ],
    })
  );

  // Markdown body
  const bodyParagraphs = parseMarkdownToParagraphs(input.markdownContent);
  children.push(...bodyParagraphs);

  // Footer
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 480 },
      children: [
        new TextRun({
          text: "Generated by The Founders Office™",
          italics: true,
          color: "888888",
          size: 18,
        }),
      ],
    })
  );

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  return Packer.toBuffer(doc);
}

/**
 * Build a safe .docx filename for a deliverable.
 * e.g. "Q1 2026 Review Prep - Ginny Test - 2026-05-27.docx"
 */
export function buildDeliverableFilename(
  title: string,
  clientName: string,
  generatedAt: string
): string {
  const safeTitle = title.replace(/[^\w\s\-–—]/g, "").trim().replace(/\s+/g, " ");
  const safeClient = clientName.replace(/[^\w\s-]/g, "").trim().replace(/\s+/g, " ");
  // generatedAt is expected as YYYY-MM-DD or an ISO timestamp; extract date portion
  const datePart = generatedAt.slice(0, 10);
  return `${safeTitle} - ${safeClient} - ${datePart}.docx`;
}
